# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FU0P2tTH_Rla5LvlYlqwGu-mD1uGg6Q6
"""

books = [
    "Koku,Patrick Suskind,1985,264",
    "Kardeşimin Hikayesi, Zülfü Livaneli, 2013, 334",
    "Kendine Ait Bir Oda, Virginia Woolf, 1929, 128"
]

with open("books.txt", "w") as file:
    for book in books:
        file.write(f"{book}\n")
import os

class Library:
    def __init__(self):
        self.file_name = 'books.txt'
        self.file = open(self.file_name, 'a+')

    def __del__(self):
        self.file.close()

    def list_books(self):
        self.file.seek(0)
        lines = self.file.readlines()
        for line in lines:
            book_info = line.strip().split(',')
            print(f"Book: {book_info[0]}")
            print(f"Author: {book_info[1]}")
            print(f"Release Date: {book_info[2]}")
            print(f"Number of Pages: {book_info[3]}")
            print("--------------------------------")

    def add_book(self):
        book_title = input("Enter book title: ")
        book_author = input("Enter book author: ")
        book_release_date = input("Enter book release date (YYYY): ")
        book_pages = input("Enter number of pages: ")
        book_info = f"{book_title},{book_author},{book_release_date},{book_pages}\n"
        self.file.write(book_info)
        print("Book added successfully.")

    def remove_book(self):
        book_title = input("Enter book title to remove: ")
        lines = self.file.readlines()
        self.file.seek(0)
        self.file.truncate()
        for line in lines:
            book_info = line.strip().split(',')
            if book_info[0] != book_title:
                self.file.write(line)
        print("Book removed successfully.")

lib = Library()
while True:
    os.system('cls' if os.name == 'nt' else 'clear')
    print("*** MENU ***")
    print("1) List Books")
    print("2) Add Book")
    print("3) Remove Book")
    print("4) Exit")
    menu_item = int(input("Enter menu item: "))
    if menu_item == 1:
        lib.list_books()
    elif menu_item == 2:
        lib.add_book()
    elif menu_item == 3:
        lib.remove_book()
    elif menu_item == 4:
        break
    else:
        print("Invalid menu item.")
    input("Press Enter to continue...")

from google.colab import drive
drive.mount('/content/drive')